### ISSUE TITLE
TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by lansman** [pypa/setuptools_scm#9] opened 2015-06-26 06:02 UTC
Windows 7 x64, Python 2.7.10, setuptools-scm 1.5.4, mercurial 3.3.2

Create test project with setup.py:
```
from distutils.core import setup

setup(    
    version='0.0.1',
    use_scm_version=True,
    setup_requires=['setuptools_scm'],
)
```
After that:
`cd <project_dir>`
`hg init`
`python.exe -c "from setuptools_scm import get_version; get_version()"`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\ArcGIS10.2\lib\site-packages\setuptools_scm\__init__.py", line 47, in get_version
    version = version_from_scm(root)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\setuptools_scm\__init__.py", line 25, in version_from_scm
    return ep.load()(root)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\setuptools_scm\hg.py", line 21, in parse
    l = do('hg id -i -t', root).split()
  File "C:\Python27\ArcGIS10.2\lib\site-packages\setuptools_scm\utils.py", line 57, in do
    out, err, ret = do_ex(cmd, cwd)
  File "C:\Python27\ArcGIS10.2\lib\site-packages\setuptools_scm\utils.py", line 42, in do_ex
    HGPLAIN='1',
  File "C:\Python27\ArcGIS10.2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\ArcGIS10.2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by RonnyPfannschmidt** [comment] 2015-06-26 06:24
this is a duplicate of #3 .
a release with a fix will be tomorrow

**Closed** 2015-06-26 08:48 UTC
